# Generated by Django 5.2.2 on 2025-06-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Напишите название блога')),
                ('image', models.ImageField(upload_to='book/', verbose_name='Загрузите картинку')),
                ('description', models.TextField(verbose_name='Дайте описание книги')),
                ('type_book', models.CharField(choices=[('Science', 'Science'), ('Fiction', 'Fiction'), ('Adventure', 'Adventure'), ('Fantasy', 'Fantasy')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
