# Generated by Django 5.2.2 on 2025-06-17 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Book', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AddField(
            model_name='book',
            name='audio_link',
            field=models.URLField(blank=True, null=True, verbose_name='Embed-ссылка на аудиокнигу'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Напишите название книги'),
        ),
    ]
