# Generated by Django 5.2.2 on 2025-06-28 08:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_options_book_audio_link_alter_book_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='напишите отзыв')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mark', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Оценка должна быть от 1 до 5'), django.core.validators.MaxValueValidator(5, message='Оценка должна быть от 1 до 5')])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('choice_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='books')),
            ],
        ),
    ]
